spring:
  application:
    name: retail-erp-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/retailerp
    username: retailerp
    password: retailerp_dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  jwt:
    secret: "change-this-to-a-long-random-secret-string-at-least-256-bits-for-production"
    expiration-ms: 86400000